### ISSUE TITLE
Is it possible to always show all tags in the bar on all screens?

### ISSUE THREAD

**Issue by f0ff886f** [Drauthius/awesome-sharedtags#12]
Right now, when I use the default config and functions of `viewonly()` the tag I want to use is moved to my screen, and the tag disappears from the other screen.

What I would like is to have all tags uniformly on all screens, and when I select a tag it moves all clients to the current screen and if the selected tag was visible on a different screen, it would select a different tag (either the current one on the screen I pulled to, so a swap, or some other behaviour).

I don't know if this is easily achievable, but right now I have to sort of hunt around to which tag is where if I haven't memorized the list of tags in general.

**Comment by Drauthius** [comment]
Hi,
`awful.widget.taglist` only show tags that belong to a certain screen. You might be able to patch it or work around it somehow, but I haven't explored it myself. 
I don't think it makes sense for this plugin to create multiple tags on different screens and move the clients (programs) around instead of the tags.

**Comment by sigprof** [comment]
Actually it is possible to set the `source` property for `awful.widget.taglist`, so that it would display all tags:
- https://github.com/awesomeWM/awesome/commit/96bbbc82f33470b52be1a2500998b836bb574a5b added the feature
- https://github.com/awesomeWM/awesome/commit/a3b753205638c6b75b3f3b2b624b0a9e20c57d94 allowed setting the `source` property for an existing widget

So you can add something like
```lua
    source = function() return tags end,
```
to the widget properties for `awful.widget.taglist`, and then that widget would display all tags.  However, the `awful.widget.taglist.taglist_label` function, which formats the tag labels for display, checks only the `selected` property of the tag and does not look at the `screen` property, therefore you may not be able to distinguish the tag selected on the current screen from a tag selected on a different screen.  You may be able to fix that with a custom `update_function` for the widget.
